[package]
name = "gst-plugin-webrtc-signalling-protocol"
version.workspace = true
edition.workspace = true
authors = ["Mathieu Duponchelle <mathieu@centricular.com>"]
license = "MPL-2.0"
description = "GStreamer WebRTC sink default protocol"
repository.workspace = true
rust-version.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[package.metadata.gstreamer]
release_date = "2025-12-02"
