[package]
name = "gst-plugin-webrtc-signalling-protocol"
version = "0.12.0-alpha.1"
edition = "2021"
authors = ["Mathieu Duponchelle <mathieu@centricular.com>"]
license = "MPL-2.0"
description = "GStreamer WebRTC sink default protocol"
repository = "https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs"
rust-version = "1.70"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
