[package]
name="webrtcsink-protocol"
version = "0.1.0"
edition = "2018"
authors = ["Mathieu Duponchelle <mathieu@centricular.com>"]
license = "MPL-2.0"
description = "GStreamer WebRTC sink default protocol"
repository = "https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
