[package]
name = "gst-plugin-webrtchttp"
version.workspace = true
authors = ["Taruntej Kanakamalla <taruntej@asymptotic.io"]
repository.workspace = true
license = "MPL-2.0"
edition.workspace = true
description = "GStreamer WebRTC Plugin for WebRTC HTTP protocols (WHIP/WHEP)"
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gst.workspace = true
gst-webrtc = { workspace = true, features = ["v1_18"] }
gst-sdp.workspace = true
reqwest = { version = "0.12", default-features = false, features = ["charset", "http2", "system-proxy", "rustls-tls"] }
rustls = { version = "0.23", default-features = false, features = ["std", "ring"] }
parse_link_header = {version = "0.4", features = ["url"]}
tokio = { version = "1.20.1", default-features = false, features = ["time", "rt-multi-thread"] }
futures = "0.3.23"
bytes = "1"
async-recursion = "1.0.0"

[lib]
name = "gstwebrtchttp"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[build-dependencies]
gst-plugin-version-helper.workspace = true

[features]
static = []
capi = []
doc = []

[package.metadata.capi]
min_version = "0.9.21"

[package.metadata.capi.header]
enabled = false

[package.metadata.capi.library]
install_subdir = "gstreamer-1.0"
versioning = false
import_library = false

[package.metadata.capi.pkg_config]
requires_private = "gstreamer-1.0, gstreamer-base-1.0, gobject-2.0, glib-2.0, gstreamer-sdp-1.0, gstreamer-webrtc-1.0"

[package.metadata.gstreamer]
release_date = "2025-07-16"
