[package]
name = "gst-plugin-ffv1"
version.workspace = true
authors = ["Arun Raghavan <arun@asymptotic.io>"]
repository.workspace = true
license = "MIT OR Apache-2.0"
description = "GStreamer FFV1 Decoder Plugin"
edition.workspace = true
rust-version.workspace = true

[dependencies]
byte-slice-cast = "1"
ffv1 = { git = "https://github.com/rust-av/ffv1.git", rev = "bd9eabfc14c9ad53c37b32279e276619f4390ab8" }
gst = { workspace = true, features = ["v1_18"] }
gst-video = { workspace = true, features = ["v1_18"] }

[dev-dependencies]
gst-check = { workspace = true, features = ["v1_18"] }
[lib]
name = "gstffv1"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[build-dependencies]
gst-plugin-version-helper.workspace = true

[features]
static = []
capi = []
doc = ["gst/v1_18"]

[package.metadata.capi]
min_version = "0.9.21"

[package.metadata.capi.header]
enabled = false

[package.metadata.capi.library]
install_subdir = "gstreamer-1.0"
versioning = false
import_library = false

[package.metadata.capi.pkg_config]
requires_private = "gstreamer-1.0, gstreamer-base-1.0, gstreamer-video-1.0, gobject-2.0, glib-2.0"

[package.metadata.gstreamer]
release_date = "2025-09-18"
