[package]
name = "gst-plugin-fallbackswitch"
version.workspace = true
authors = ["Sebastian Dr√∂ge <sebastian@centricular.com>", "Jan Schmidt <jan@centricular.com>"]
repository.workspace = true
license = "MPL-2.0"
edition.workspace = true
rust-version.workspace = true
description = "GStreamer Fallback Switcher and Source Plugin"

[dependencies]
gst.workspace = true
gst-base.workspace = true
gst-audio.workspace = true
gst-video.workspace = true
parking_lot = "0.12"
rand = "0.10"

[dev-dependencies]
gst-app.workspace = true
gst-check.workspace = true
gst-plugin-gtk4.workspace = true
gtk.workspace = true
gio.workspace = true
clap = { version = "4", features = ["derive"] }
futures = "0.3"

[lib]
name = "gstfallbackswitch"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[example]]
name = "gtk-fallbackswitch"
path = "examples/gtk_fallbackswitch.rs"
required-features = ["gtk", "gio", "gst-plugin-gtk4"]

[[example]]
name = "fallbacksrc"
path = "examples/fallbacksrc.rs"

[build-dependencies]
gst-plugin-version-helper.workspace = true

[features]
default = ["v1_20"]
static = []
capi = []
doc = ["gst/v1_18"]
v1_20 = ["gst/v1_20"]

[package.metadata.capi]
min_version = "0.9.21"

[package.metadata.capi.header]
enabled = false

[package.metadata.capi.library]
install_subdir = "gstreamer-1.0"
versioning = false
import_library = false

[package.metadata.capi.pkg_config]
requires_private = "gstreamer-1.0, gstreamer-base-1.0, gstreamer-audio-1.0, gstreamer-video-1.0, gobject-2.0, glib-2.0, gmodule-2.0"
