[package]
name = "gst-plugin-fallbackswitch"
version = "0.7.2"
authors = ["Sebastian Dr√∂ge <sebastian@centricular.com>"]
repository = "https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs"
license = "LGPL-2.1-or-later"
edition = "2018"
description = "Fallback Switcher Plugin"

[dependencies]
libc = { version = "0.2", optional = true }
gst = { package = "gstreamer", version = "0.17", features = ["v1_14"] }
gst-base = { package = "gstreamer-base", version = "0.17", features = ["v1_16"] }
gst-audio = { package = "gstreamer-audio", version = "0.17", features = ["v1_14"] }
gst-video = { package = "gstreamer-video", version = "0.17", features = ["v1_14"] }
gtk = { version = "0.14", optional = true }
gio = { version = "0.14", optional = true }
once_cell = "1.0"

[dev-dependencies]
gst-app = { package = "gstreamer-app", version = "0.17",  features = ["v1_14"]}
gst-check = { package = "gstreamer-check", version = "0.17",  features = ["v1_14"]}

[lib]
name = "gstfallbackswitch"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[example]]
name = "gtk-fallbackswitch"
path = "examples/gtk_fallbackswitch.rs"
required-features = ["gtk", "gio"]

[build-dependencies]
gst-plugin-version-helper = { version = "0.7.0", path="../../version-helper" }
cc = "1.0"
pkg-config = "0.3"

[features]
default = ["libc"]
v1_18 = ["gst-base/v1_18"]
v1_20 = ["v1_18", "gst/v1_20"]
# We already use 1.14 which is new enough for static build
static = []
capi = []

[package.metadata.capi]
min_version = "0.7.0"

[package.metadata.capi.header]
enabled = false

[package.metadata.capi.library]
install_subdir = "gstreamer-1.0"
versioning = false

[package.metadata.capi.pkg_config]
requires_private = "gstreamer-1.0, gstreamer-base-1.0, gobject-2.0, glib-2.0, gmodule-2.0"
