[package]
name = "gst-plugin-http"
version = "0.1.0"
authors = ["Sebastian Dr√∂ge <sebastian@centricular.com>"]
repository = "https://github.com/sdroege/rsplugin"
license = "MIT/Apache-2.0"

[dependencies]
url = "1.1"
gst-plugin = { path="../gst-plugin" }
reqwest = "0.5"
slog = "2.0"

[lib]
name = "gstrshttp"
crate-type = ["cdylib"]
path = "src/lib.rs"
