[package]
name = "gst-plugin-webp"
version = "0.7.1"
authors = ["Mathieu Duponchelle <mathieu@centricular.com>"]
license = "LGPL-2.1-or-later"
edition = "2018"
description = "WebP Plugin"
repository = "https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs"

[dependencies]
once_cell = "1.0"
libwebp-sys2 = { version = "0.1.2", features = ["demux", "0_5"] }

[dependencies.gst]
version = "0.17"
package="gstreamer"

[dependencies.gst-video]
version = "0.17"
package="gstreamer-video"

[dev-dependencies]
pretty_assertions = "0.7"

[dev-dependencies.gst-check]
version = "0.17"
package="gstreamer-check"

[lib]
name = "gstrswebp"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[build-dependencies]
gst-plugin-version-helper = { version = "0.7.0", path="../../version-helper" }

[features]
# GStreamer 1.14 is required for static linking
static = ["gst/v1_14"]

[package.metadata.capi]
min_version = "0.7.0"

[package.metadata.capi.header]
enabled = false

[package.metadata.capi.library]
install_subdir = "gstreamer-1.0"
versioning = false

[package.metadata.capi.pkg_config]
requires_private = "gstreamer-1.0, gstreamer-video-1.0, gobject-2.0, glib-2.0, gmodule-2.0"
