[package]
name = "gst-plugin-togglerecord"
version = "0.1.0"
authors = ["Sebastian Dr√∂ge <sebastian@centricular.com>"]
license = "LGPL-2.1+"

[dependencies]
glib = "0.4"
gstreamer = { version = "0.10", features = ["v1_10"] }
gstreamer-video = { version = "0.10", features = ["v1_10"] }
gst-plugin = { version = "0.1", path = "../gst-plugin" }
gtk = { version = "0.3", features = ["v3_6"], optional = true }
gio = { version = "0.3", optional = true }
send-cell = { version = "0.1", optional = true }

[dev-dependencies]
either = "1.0"

[lib]
name = "gsttogglerecord"
crate-type = ["cdylib"]
path = "src/lib.rs"

[[example]]
name = "gtk-recording"
path = "examples/gtk_recording.rs"
required-features = ["gtk", "gio", "send-cell"]

