[package]
name = "gst-plugin-uriplaylistbin"
version = "0.11.0-alpha.1"
authors = ["Guillaume Desmottes <guillaume.desmottes@onestream.live>"]
repository = "https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs"
license = "MPL-2.0"
edition = "2021"
description = "GStreamer Playlist Playback Plugin"
rust-version = "1.70"

[dependencies]
gst = { package = "gstreamer", git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs" }
anyhow = "1"
clap = { version = "4", optional = true, features = ["derive"] }
thiserror = "1"

[dev-dependencies]
gst-app = { package = "gstreamer-app", git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs" }
url = "2.2"
more-asserts = "0.3"

[lib]
name = "gsturiplaylistbin"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[example]]
name = "playlist"
path = "examples/playlist.rs"
required-features = ["clap"]

[build-dependencies]
gst-plugin-version-helper = { path="../../version-helper" }

[features]
static = []
capi = []
doc = ["gst/v1_18"]

[package.metadata.capi]
min_version = "0.8.0"

[package.metadata.capi.header]
enabled = false

[package.metadata.capi.library]
install_subdir = "gstreamer-1.0"
versioning = false

[package.metadata.capi.pkg_config]
requires_private = "gstreamer-1.0, gobject-2.0, glib-2.0, gmodule-2.0"
