[package]
name = "gst-plugin-uriplaylistbin"
version.workspace = true
authors = ["Guillaume Desmottes <guillaume.desmottes@onestream.live>"]
repository.workspace = true
license = "MPL-2.0"
edition.workspace = true
description = "GStreamer Playlist Playback Plugin"
rust-version.workspace = true

[dependencies]
gst = { workspace = true, features = ["v1_24"] }
anyhow = "1"
clap = { version = "4", optional = true, features = ["derive"] }
thiserror = "2"
once_cell.workspace = true

[dev-dependencies]
gst-app.workspace = true
url = "2.2"
more-asserts = "0.3"
tempfile = "3"

[lib]
name = "gsturiplaylistbin"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[[example]]
name = "playlist"
path = "examples/playlist.rs"
required-features = ["clap"]

[build-dependencies]
gst-plugin-version-helper.workspace = true

[features]
static = []
capi = []
doc = ["gst/v1_18"]

[package.metadata.capi]
min_version = "0.9.21"

[package.metadata.capi.header]
enabled = false

[package.metadata.capi.library]
install_subdir = "gstreamer-1.0"
versioning = false
import_library = false

[package.metadata.capi.pkg_config]
requires_private = "gstreamer-1.0, gobject-2.0, glib-2.0, gmodule-2.0"
