[package]
name = "gst-plugin-analytics"
version.workspace = true
authors = ["Benjamin Gaignard <benjamin.gaignard@collabora.com>", "Sebastian Dr√∂ge <sebastian@centricular.com>"]
repository.workspace = true
license = "MPL-2.0"
description = "GStreamer Rust Analytics Plugin"
edition.workspace = true
rust-version.workspace = true

[lib]
name = "gstrsanalytics"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
gst = { workspace = true, features = ["v1_24"] }
gst-rtp = { workspace = true, features = ["v1_24"] }
gst-base = { workspace = true, features = ["v1_24"] }
gst-video = { workspace = true, features = ["v1_24"] }
gst-analytics = { workspace = true }
chrono = { version = "0.4.31", default-features = false }
xmltree = "0.11"
glib = { workspace = true, features = ["v2_62"] }

[dev-dependencies]
gst-check.workspace = true

[build-dependencies]
gst-plugin-version-helper.workspace = true

[features]
static = []
capi = []
doc = []
v1_28 = ["gst-analytics/v1_28"]

[[test]]
name = "analyticscombiner"
required-features = ["v1_28"]

[[test]]
name = "analyticssplitter"
required-features = ["v1_28"]

[package.metadata.capi]
min_version = "0.9.21"

[package.metadata.capi.header]
enabled = false

[package.metadata.capi.library]
install_subdir = "gstreamer-1.0"
versioning = false
import_library = false

[package.metadata.capi.pkg_config]
requires_private = "gstreamer-1.0, gstreamer-base-1.0, gobject-2.0, glib-2.0, gmodule-2.0, gstreamer-analytics-1.0"

[package.metadata.gstreamer]
release_date = "2025-07-16"
