[package]
name = "gst-plugin-flv"
version = "0.1.0"
authors = ["Sebastian Dr√∂ge <sebastian@centricular.com>"]
repository = "https://github.com/sdroege/gst-plugin-rs"
license = "MIT/Apache-2.0"

[dependencies]
url = "1.1"
gst-plugin = { path="../gst-plugin" }
gst-plugin-simple = { path="../gst-plugin-simple" }
gstreamer = { git = "https://github.com/sdroege/gstreamer-rs" }
num-rational = { version = "0.1", default-features = false, features = [] }
nom = "3.0"
flavors = {git = "https://github.com/rust-av/flavors.git"}
muldiv = "0.1"

[lib]
name = "gstrsflv"
crate-type = ["cdylib"]
path = "src/lib.rs"
