[package]
name = "gst-plugin-version-helper"
version = "0.8.1"
authors = ["Sajeer Ahamed <ahamedsajeer.15.15@cse.mrt.ac.lk>",
           "Sebastian Dr√∂ge <sebastian@centricular.com>"]
categories = ["development-tools"]
description = "build.rs helper function for GStreamer plugin metadata"
repository.workspace = true
license = "MIT"
homepage = "https://gstreamer.freedesktop.org"
keywords = ["gstreamer", "multimedia", "cargo"]
edition.workspace = true
rust-version = "1.69"

[dependencies]
chrono = { version = "0.4.23", default-features = false, features = ["std", "clock"] }
toml_edit = { version = "0.22.8", default-features = false, features = ["parse"] }

[package.metadata.gstreamer]
release_date = "2025-03-04"
