[package]
name = "gst-plugin-burn"
version.workspace = true
authors = ["Sebastian Dr√∂ge <sebastian@centricular.com>"]
repository.workspace = true
license = "MPL-2.0 AND (MIT OR Apache-2.0)"
description = "GStreamer Burn plugin"
edition.workspace = true
rust-version.workspace = true

[dependencies]
glib.workspace = true
gst = { workspace = true, features = ["v1_28"] }
gst-base = { workspace = true, features = ["v1_28"] }
gst-analytics = { workspace = true, features = ["v1_28"] }
gst-video = { workspace = true, features = ["v1_28"] }
burn = { version = "0.19", default-features = false, features = ["ndarray"] }
burn-import = { version = "0.19", default-features = false, features = ["pytorch"] }
dirs = { version = "6", optional = true }
serde = { version = "1.0.192", default-features = false, features = ["derive", "alloc"] }
byte-slice-cast = "1"
itertools = "0.14"
anyhow = "1"

[build-dependencies]
gst-plugin-version-helper.workspace = true

[lib]
name = "gstburn"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[features]
static = []
capi = []
doc = []
pretrained = ["burn/network", "dep:dirs"]
vulkan = ["burn/vulkan"]
default = ["pretrained"]

[package.metadata.capi]
min_version = "0.9.21"

[package.metadata.capi.header]
enabled = false

[package.metadata.capi.library]
install_subdir = "gstreamer-1.0"
versioning = false
import_library = false

[package.metadata.capi.pkg_config]
requires_private = "gstreamer-1.0, gstreamer-base-1.0, gstreamer-video-1.0, gstreamer-analytics-1.0, gobject-2.0, glib-2.0, gmodule-2.0"

