[package]
name = "gst-plugin-rusoto"
version = "0.6.0"
authors = ["Arun Raghavan <arun@arunraghavan.net>",
           "Jordan Petridis <jordan@centricular.com>",
           "Mathieu Duponchelle <mathieu@centricular.com>"]
repository = "https://gitlab.freedesktop.org/gstreamer/gst-plugins-rs"
license = "MIT/Apache-2.0"
description = "Amazon Web Services plugin"
edition = "2018"

[dependencies]
bytes = "1.0"
futures = "0.3"
gst = { package = "gstreamer", git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs", features = ["v1_12"] }
gst-base = { package = "gstreamer-base", git = "https://gitlab.freedesktop.org/gstreamer/gstreamer-rs", features = ["v1_12"] }
rusoto_core = "0.46"
rusoto_s3 = "0.46"
rusoto_credential = "0.46"
rusoto_signature = "0.46"
url = "2"
percent-encoding = "2"
tokio = { version = "1.0", features = [ "rt-multi-thread" ] }
async-tungstenite = { version = "0.13", features = ["tokio", "tokio-runtime", "tokio-native-tls"] }
nom = "6"
crc = "1.8.1"
byteorder = "1.3.4"
once_cell = "1.0"
serde = "1"
serde_derive = "1"
serde_json = "1"
atomic_refcell = "0.1"

[lib]
name = "gstrusoto"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[build-dependencies]
gst-plugin-version-helper = { path="../../version-helper" }

[features]
# GStreamer 1.14 is required for static linking
static = ["gst/v1_14"]

[package.metadata.capi]
min_version = "0.7.0"

[package.metadata.capi.header]
enabled = false

[package.metadata.capi.library]
install_subdir = "gstreamer-1.0"
versioning = false

[package.metadata.capi.pkg_config]
requires_private = "gstreamer-1.0, gstreamer-base-1.0, gobject-2.0, glib-2.0, gmodule-2.0, libssl"
