[package]
name = "gst-plugin-tutorial"
version = "0.1.0"
authors = ["Sebastian Dr√∂ge <sebastian@centricular.com>"]
repository = "https://github.com/sdroege/gst-plugin-rs"
license = "MIT/Apache-2.0"

[dependencies]
gst-plugin = { path="../gst-plugin" }
glib = { git = "https://github.com/gtk-rs/glib" }

# Temporary (preview Query changes)
#gstreamer = { git = "https://github.com/sdroege/gstreamer-rs" }
#gstreamer-base = { git = "https://github.com/sdroege/gstreamer-rs" }
#gstreamer-video = { git = "https://github.com/sdroege/gstreamer-rs" }
gstreamer = { git = "https://github.com/fengalin/gstreamer-rs", branch = "query_deref" }
gstreamer-base = { git = "https://github.com/fengalin/gstreamer-rs", branch = "query_deref" }
gstreamer-video = { git = "https://github.com/fengalin/gstreamer-rs", branch = "query_deref" }

[lib]
name = "gstrstutorial"
crate-type = ["cdylib"]
path = "src/lib.rs"
