[package]
name = "gst-plugin-tracers"
version.workspace = true
authors = ["Guillaume Desmottes <guillaume.desmottes@onestream.live>"]
repository.workspace = true
license = "MPL-2.0"
edition.workspace = true
description = "GStreamer Rust tracers plugin"
rust-version.workspace = true

[dependencies]
gst.workspace = true
anyhow = "1"
regex = "1"
atomic_refcell = "0.1"
pcap-file = "2"
etherparse = "0.19.0"
chrono = "0.4.35"
walkdir = "2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.11"
async-tungstenite = { version = "0.31", features = ["tokio-runtime", "url"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
url = "2"
futures = "0.3"

[target.'cfg(unix)'.dependencies]
signal-hook = "0.3"

[lib]
name = "gstrstracers"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[build-dependencies]
gst-plugin-version-helper.workspace = true

[features]
static = []
capi = []
doc = ["gst/v1_18"]
v1_22 = ["gst/v1_22"]
v1_26 = ["gst/v1_26"]

[package.metadata.capi]
min_version = "0.9.21"

[package.metadata.capi.header]
enabled = false

[package.metadata.capi.library]
install_subdir = "gstreamer-1.0"
versioning = false
import_library = false

[package.metadata.capi.pkg_config]
requires_private = "gstreamer-1.0, gobject-2.0, glib-2.0, gmodule-2.0"

[package.metadata.gstreamer]
release_date = "2025-09-18"
